version: '3'
services:

  #Aplicação
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: app-jUnesc
    volumes:
      - ./jUnesc:/var/www
    networks:
      frontend:
      database:
        ipv4_address: 172.28.1.4

  #Database
  database:
    image: postgres:9.5-alpine
    container_name: db-jUnesc
    volumes:
        - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=JUnesc
    ports:
      - "5432:5432"
    networks:
      database:
        ipv4_address: 172.28.1.3

  #Web Server
  web:
    image: nginx
    container_name: web-jUnesc
    volumes:
      - ./web.conf:/etc/nginx/conf.d/default.conf
      - ./jUnesc:/var/www/
    ports:
      - 8080:80
    networks: 
      - frontend
      
#Volumes
volumes:
  dbdata:

networks:
    frontend:
    database:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16